require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'cookbooks/**/*'
    - 'data/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'solr/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

### Layout.

Layout/ArgumentAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true

Layout/BlockAlignment:
  Enabled: false

Layout/ClassStructure:
  Enabled: true

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/HashAlignment:
  Enabled: false

Layout/HeredocArgumentClosingParenthesis:
  Enabled: true

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 145
  Exclude:
    - 'app/database_scripts/database_scripts/**/*'

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

### Lint.

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousRegexpLiteral:
  Enabled: true
  Exclude:
    - 'features/step_definitions/**/*'
    - 'spec/**/*'

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true
  Exclude:
    - 'lib/tasks/**/*.rake'

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: false

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true
  Exclude:
    - 'spec/factories/**/*' # For transient attributes.

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/HashCompareByIdentity:
  Enabled: true

Lint/HeredocMethodCallPosition:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/RedundantSafeNavigation:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - delegate

Lint/UselessMethodDefinition:
  Enabled: false

Lint/UselessTimes:
  Enabled: true

# Metrics.

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/**/*'

Metrics/ClassLength:
  Enabled: false
  Max: 100
  CountAsOne:
    - array
    - hash
    - heredoc
  Exclude:
    - 'app/cleanup/**/*'
    - 'app/controllers/quick_and_dirty_fixes_controller.rb'
    - 'app/database_scripts/**/*'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
  Exclude:
    - 'app/database_scripts/database_scripts/**/*'

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 14
  Enabled: false

### Naming.

Naming/AccessorMethodName:
  Enabled: true

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Naming/PredicateName:
  Enabled: true

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*'

### Rails.

Rails:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/AfterCommitOverride:
  Enabled: true

Rails/BulkChangeTable:
  Enabled: false

Rails/ContentTag:
  Enabled: true

Rails/DefaultScope:
  Enabled: true

Rails/Delegate:
  Enabled: false

Rails/FindById:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/InverseOf:
  Enabled: false

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/OutputSafety:
  Enabled: false
  Exclude:
    - 'app/database_scripts/database_scripts/**/*'

Rails/RakeEnvironment:
  Enabled: false

Rails/ReflectionClassName:
  Enabled: false

Rails/RenderInline:
  Enabled: false

Rails/RenderPlainText:
  Enabled: true

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'

Rails/ShortI18n:
  Enabled: true

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/WhereExists:
  Enabled: false

Rails/WhereNot:
  Enabled: false

# Indexes are not case sensitive in MySQL. Revisit if we ever migrate to Postgres.
Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/Validation:
  Enabled: false

### RSpec.

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/FactoryBot/CreateList:
  EnforcedStyle: n_times

RSpec/LetSetup:
  Exclude:
    - 'spec/operations/**/*'

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/NotToNot:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

### Performance.

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/CollectionLiteralInLoop:
  Enabled: true

Performance/DeletePrefix:
  Enabled: true

Performance/DeleteSuffix:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/Sum:
  Enabled: true

### Style.

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AccessorGrouping:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true

Style/ClassCheck:
  EnforcedStyle: is_a?

Style/ClassEqualityComparison:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/CommentAnnotation:
  Keywords:
    - TODO
    - FIXME
    - OPTIMIZE
    - PERFORMANCE
    - HACK
    - REVIEW
    - NOTE
    - TMPCLEANUP

Style/DateTime:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ExponentialNotation:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always_true

Style/GlobalStdStream:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: true

Style/Lambda:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses_except_multiline

Style/MultilineBlockChain:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: true

Style/OptionHash:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/Send:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: false

Style/StderrPuts:
  Enabled: true

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringMethods:
  Enabled: true

Style/SwapValues:
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInBlockArgs:
  Enabled: true

Style/WordArray:
  Enabled: false
