development: &development
  adapter: mysql2
  database: antcat_test_ci
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  timeout: 5000
  port: <%= ENV['DB_PORT'] %>

test: &test
  adapter: mysql2
  database: antcat_test_ci
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  timeout: 5000
  port: <%= ENV['DB_PORT'] %>
