development: &development
  adapter: mysql2
  database: antcat_test_ci
  pool: 5
  username: root
  password: root
  timeout: 5000
  port: "<%= ENV['DB_PORT'] %>"

test: &test
  adapter: mysql2
  database: antcat_test_ci
  pool: 5
  username: root
  password: root
  timeout: 5000
  port: "<%= ENV['DB_PORT'] %>"
