# Engine Yard Cloud Deploy Options
#
# See:
# https://support.cloud.engineyard.com/entries/20996661-customize-your-deployment-on-engine-yard-cloud
# https://github.com/engineyard/engineyard-serverside/blob/master/lib/engineyard-serverside/configuration.rb
# Default configs: https://github.com/engineyard/engineyard-serverside#eyyml-configuration

defaults:
  migrate: true
  migration_command: rake db:migrate --trace
  precompile_assets: true
